package com.adastra;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;


public class adastra implements ModInitializer{

///添加组
public static final ItemGroup ITEM_GROUP = FabricItemGroupBuilder.build(
    new Identifier("adastra", "adastra"),
    () -> new ItemStack(Blocks.COBBLESTONE));

///添加物品
public static final Block armored_glass = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block ciliutilu = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block duanlu = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block gjhxfyq = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block gwfys = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block dianhulu = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block yalicang = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block ganliushi = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block zhengliuta = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block htqwaike = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block beishaolu = new Block(FabricBlockSettings.of(Material.METAL));
public static final Block dianjieqi = new Block(FabricBlockSettings.of(Material.METAL));
public static final Item acid_container=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item alkali_container=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item current_arranger=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item electric_magnet=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item permanent_magnet=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item magnetic_shield=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item acopper_coil=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item acopper_coils=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item asilver_coil=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item asilver_coils=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ata_coil=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ata_coils=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item mg_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item mn_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ta_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item rh_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pd_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item mgal_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pure_cu_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pure_pd_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pure_ta_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pure_rh_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pure_pt_ingot=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item hot_mn_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item hot_cr_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item mn_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item cr_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item st_mn_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item st_cr_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item st_w_steel=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item advanced_heat_frame=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item advanced_pressure_frame=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ptef_frame=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item reactor=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item turbine_fan=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pumper=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item motor=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item fuel_tank=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item zheguangyi=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item luojixp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item huancunxp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item shuweixp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item jisuanxp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item yalicgq=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item gaowencgq=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item canshucore=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item maincore=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item donglicore=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item yunzai_eng=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item tance_eng=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item le_ceramic=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pe_ceramic=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pressure_ceramic=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pm_ceramic=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item lm_ceramic=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item redst_jingp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item silicon_jingp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item prh_jingp=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item si_c=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item si3_n4=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ge3_n4=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ca2_c2=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item na_cl=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item mg_cl2=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item na_br=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item al2_o3=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item fe2_o3=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item fe3_o4=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item cu_o=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item zn_o=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item pb_o=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item ca_co3=new Item(new Item.Settings().group(adastra.ITEM_GROUP));
public static final Item na2b4_o7=new Item(new Item.Settings().group(adastra.ITEM_GROUP));

public void onInitialize(){

Registry.register(Registry.ITEM,new Identifier("adastra","acid_container"),acid_container);
Registry.register(Registry.ITEM,new Identifier("adastra","alkali_container"),alkali_container);
Registry.register(Registry.ITEM,new Identifier("adastra","current_arranger"),current_arranger);
Registry.register(Registry.ITEM,new Identifier("adastra","electric_magnet"),electric_magnet);
Registry.register(Registry.ITEM,new Identifier("adastra","permanent_magnet"),permanent_magnet);
Registry.register(Registry.ITEM,new Identifier("adastra","magnetic_shield"),magnetic_shield);
Registry.register(Registry.ITEM,new Identifier("adastra","acopper_coil"),acopper_coil);
Registry.register(Registry.ITEM,new Identifier("adastra","acopper_coils"),acopper_coils);
Registry.register(Registry.ITEM,new Identifier("adastra","asilver_coil"),asilver_coil);
Registry.register(Registry.ITEM,new Identifier("adastra","asilver_coils"),asilver_coils);
Registry.register(Registry.ITEM,new Identifier("adastra","ata_coil"),ata_coil);
Registry.register(Registry.ITEM,new Identifier("adastra","ata_coils"),ata_coils);
Registry.register(Registry.ITEM,new Identifier("adastra","mg_ingot"),mg_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","mn_ingot"),mn_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","ta_ingot"),ta_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","rh_ingot"),rh_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","pd_ingot"),pd_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","mgal_ingot"),mgal_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","pure_cu_ingot"),pure_cu_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","pure_pd_ingot"),pure_pd_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","pure_ta_ingot"),pure_ta_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","pure_rh_ingot"),pure_rh_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","pure_pt_ingot"),pure_pt_ingot);
Registry.register(Registry.ITEM,new Identifier("adastra","hot_mn_steel"),hot_mn_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","hot_cr_steel"),hot_cr_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","mn_steel"),mn_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","cr_steel"),cr_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","st_mn_steel"),st_mn_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","st_cr_steel"),st_cr_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","st_w_steel"),st_w_steel);
Registry.register(Registry.ITEM,new Identifier("adastra","advanced_heat_frame"),advanced_heat_frame);
Registry.register(Registry.ITEM,new Identifier("adastra","advanced_pressure_frame"),advanced_pressure_frame);
Registry.register(Registry.ITEM,new Identifier("adastra","ptef_frame"),ptef_frame);
Registry.register(Registry.ITEM,new Identifier("adastra","reactor"),reactor);
Registry.register(Registry.ITEM,new Identifier("adastra","turbine_fan"),turbine_fan);
Registry.register(Registry.ITEM,new Identifier("adastra","pumper"),pumper);
Registry.register(Registry.ITEM,new Identifier("adastra","motor"),motor);
Registry.register(Registry.ITEM,new Identifier("adastra","fuel_tank"),fuel_tank);
Registry.register(Registry.ITEM,new Identifier("adastra","zheguangyi"),zheguangyi);
Registry.register(Registry.ITEM,new Identifier("adastra","luojixp"),luojixp);
Registry.register(Registry.ITEM,new Identifier("adastra","huancunxp"),huancunxp);
Registry.register(Registry.ITEM,new Identifier("adastra","shuweixp"),shuweixp);
Registry.register(Registry.ITEM,new Identifier("adastra","jisuanxp"),jisuanxp);
Registry.register(Registry.ITEM,new Identifier("adastra","yalicgq"),yalicgq);
Registry.register(Registry.ITEM,new Identifier("adastra","gaowencgq"),gaowencgq);
Registry.register(Registry.ITEM,new Identifier("adastra","canshucore"),canshucore);
Registry.register(Registry.ITEM,new Identifier("adastra","maincore"),maincore);
Registry.register(Registry.ITEM,new Identifier("adastra","donglicore"),donglicore);
Registry.register(Registry.ITEM,new Identifier("adastra","yunzai_eng"),yunzai_eng);
Registry.register(Registry.ITEM,new Identifier("adastra","tance_eng"),tance_eng);
Registry.register(Registry.ITEM,new Identifier("adastra","le_ceramic"),le_ceramic);
Registry.register(Registry.ITEM,new Identifier("adastra","pe_ceramic"),pe_ceramic);
Registry.register(Registry.ITEM,new Identifier("adastra","pressure_ceramic"),pressure_ceramic);
Registry.register(Registry.ITEM,new Identifier("adastra","pm_ceramic"),pm_ceramic);
Registry.register(Registry.ITEM,new Identifier("adastra","lm_ceramic"),lm_ceramic);
Registry.register(Registry.ITEM,new Identifier("adastra","redst_jingp"),redst_jingp);
Registry.register(Registry.ITEM,new Identifier("adastra","silicon_jingp"),silicon_jingp);
Registry.register(Registry.ITEM,new Identifier("adastra","prh_jingp"),prh_jingp);
Registry.register(Registry.ITEM,new Identifier("adastra","si_c"),si_c);
Registry.register(Registry.ITEM,new Identifier("adastra","si3_n4"),si3_n4);
Registry.register(Registry.ITEM,new Identifier("adastra","ge3_n4"),ge3_n4);
Registry.register(Registry.ITEM,new Identifier("adastra","ca2_c2"),ca2_c2);
Registry.register(Registry.ITEM,new Identifier("adastra","na_cl"),na_cl);
Registry.register(Registry.ITEM,new Identifier("adastra","mg_cl2"),mg_cl2);
Registry.register(Registry.ITEM,new Identifier("adastra","na_br"),na_br);
Registry.register(Registry.ITEM,new Identifier("adastra","al2_o3"),al2_o3);
Registry.register(Registry.ITEM,new Identifier("adastra","fe2_o3"),fe2_o3);
Registry.register(Registry.ITEM,new Identifier("adastra","fe3_o4"),fe3_o4);
Registry.register(Registry.ITEM,new Identifier("adastra","cu_o"),cu_o);
Registry.register(Registry.ITEM,new Identifier("adastra","zn_o"),zn_o);
Registry.register(Registry.ITEM,new Identifier("adastra","pb_o"),pb_o);
Registry.register(Registry.ITEM,new Identifier("adastra","ca_co3"),ca_co3);
Registry.register(Registry.ITEM,new Identifier("adastra","na2b4_o7"),na2b4_o7);
Registry.register(Registry.BLOCK, new Identifier("adastra", "armored_glass"),armored_glass);
Registry.register(Registry.BLOCK, new Identifier("adastra", "ciliutilu"),ciliutilu);
Registry.register(Registry.BLOCK, new Identifier("adastra", "duanlu"),duanlu);
Registry.register(Registry.BLOCK, new Identifier("adastra", "gjhxfyq"),gjhxfyq);
Registry.register(Registry.BLOCK, new Identifier("adastra", "gwfys"),gwfys);
Registry.register(Registry.BLOCK, new Identifier("adastra", "dianhulu"),dianhulu);
Registry.register(Registry.BLOCK, new Identifier("adastra", "yalicang"),yalicang);
Registry.register(Registry.BLOCK, new Identifier("adastra", "ganliushi"),ganliushi);
Registry.register(Registry.BLOCK, new Identifier("adastra", "zhengliuta"),zhengliuta);
Registry.register(Registry.BLOCK, new Identifier("adastra", "htqwaike"),htqwaike);
Registry.register(Registry.BLOCK, new Identifier("adastra", "beishaolu"),beishaolu);
Registry.register(Registry.BLOCK, new Identifier("adastra", "dianjieqi"),dianjieqi);
Registry.register(Registry.ITEM, new Identifier("adastra", "armored_glass"), new BlockItem(armored_glass, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "ciliutilu"), new BlockItem(ciliutilu, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "duanlu"), new BlockItem(duanlu, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "gjhxfyq"), new BlockItem(gjhxfyq, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "gwfys"), new BlockItem(gwfys, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "dianhulu"), new BlockItem(dianhulu, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "yalicang"), new BlockItem(yalicang, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "ganliushi"), new BlockItem(ganliushi, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "zhengliuta"), new BlockItem(zhengliuta, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "htqwaike"), new BlockItem(htqwaike, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "beishaolu"), new BlockItem(beishaolu, new Item.Settings().group(adastra.ITEM_GROUP)));
Registry.register(Registry.ITEM, new Identifier("adastra", "dianjieqi"), new BlockItem(dianjieqi, new Item.Settings().group(adastra.ITEM_GROUP)));

}

}